//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int year { get; set; }
        public int specialization_id { get; set; }
        public int clas { get; set; }
        public int lecture_at_id { get; set; }
        public int dayinweek { get; set; }
        public int hall_id { get; set; }
    
        public virtual dayinweek dayinweek1 { get; set; }
        public virtual hall hall { get; set; }
        public virtual lecture_at lecture_at { get; set; }
        public virtual specialization specialization { get; set; }
    }
}
