//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class mark
    {
        public int id { get; set; }
        [DisplayName("«·ÿ«·»")]
        public int student_id { get; set; }
        [DisplayName("«·„«œ…")]
        public int material_id { get; set; }
        [DisplayName("«·⁄·«„…")]
        public Nullable<double> mark1 { get; set; }
    
        public virtual material material { get; set; }
        public virtual student student { get; set; }
    }
}
