//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class material
    {
        public material()
        {
            this.lectures = new HashSet<lecture>();
            this.marks = new HashSet<mark>();
        }

        public int id { get; set; }
        [DisplayName("«·„«œ…")]

        public string material_name { get; set; }
    
        public virtual ICollection<lecture> lectures { get; set; }
        public virtual ICollection<mark> marks { get; set; }
    }
}
