//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class notification
    {
        public int Id { get; set; }
        [DisplayName("«·‰«‘—")]
        public int author { get; set; }
        [Required]
        [DisplayName("«·⁄‰Ê«‰")]
        public string title { get; set; }
        [DisplayName("«·‘—Õ")]
        [DataType(DataType.MultilineText)]
        public string description { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
