//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public int requester { get; set; }
        public int request_type { get; set; }
        public int status { get; set; }
    
        public virtual request_type request_type1 { get; set; }
        public virtual student student { get; set; }
        public virtual status status1 { get; set; }
    }
}
