//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class specialization
    {
        public specialization()
        {
            this.lectures = new HashSet<lecture>();
            this.students = new HashSet<student>();
        }

        public int Id { get; set; }
        [DisplayName("«·«Œ ’«’")]
        public string name { get; set; }
    
        public virtual ICollection<lecture> lectures { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}
