//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class status
    {
        public status()
        {
            this.requests = new HashSet<request>();
        }

        public int id { get; set; }
        [DisplayName("«·Õ«·…")]
        public string status1 { get; set; }
    
        public virtual ICollection<request> requests { get; set; }
    }
}
