//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class student
    {
        public student()
        {
            this.requests = new HashSet<request>();
            this.marks = new HashSet<mark>();
        }
    
        public int Id { get; set; }
        [DisplayName("«·«”„ «·ﬂ«„·")]
        public string fullname { get; set; }
        [DisplayName("«·”‰…")]
        public int year { get; set; }
        [DisplayName("«·›∆…")]
        public int clas { get; set; }
        [DisplayName("«·«Œ ’«’")]
        public int specialization_id { get; set; }
        [DisplayName("ﬂ·„… «·„—Ê—")]
        [StringLength(30, ErrorMessage = "Must be between 5 and 30 characters", MinimumLength = 5)]
        [DataType(DataType.Password)]
        public string password { get; set; }
    
        public virtual ICollection<request> requests { get; set; }
        public virtual specialization specialization { get; set; }
        public virtual ICollection<mark> marks { get; set; }
    }
}
