//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int year { get; set; }
        public int clas { get; set; }
        public int specialization_id { get; set; }
    
        public virtual specialization specialization { get; set; }
    }
}
